services:
  gateway:
#    build:
#      context: ..          # 리포 루트
#      dockerfile: gateway/Dockerfile
    image: 872759853372.dkr.ecr.ap-northeast-2.amazonaws.com/gateway:gateway-v0.0.8

    container_name: gateway-local
    ports:
      - "2031:2031"
    environment:
      - SPRING_PROFILES_ACTIVE=local
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    restart: always
#docker compose -f gateway/docker-compose.local.yml up -d
#docker compose -f gateway/docker-compose.local.yml down
#docker logs -f gateway-local