gateway:


spring:
  application:
    name: gateway
  db:
    redis:
      host: 10.0.14.108
      port: 6379

  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: 43.202.195.185
    listener:
      simple:
        prefetch: 5

eureka:
  client:
    serviceUrl:
#      defaultZone: http://43.202.195.185:8761/eureka/
      defaultZone: http://10.0.14.108:8761/eureka/