server:
  port: 2031

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh, info, metrics, prometheus

springdoc:
  swagger-ui:
    enabled: true
