#file: noinspection SpringBootApplicationYaml
spring:
  jpa:
    database-platform: com.origemite.lib.common.extend.CustomMariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        format_sql: false
        default_batch_fetch_size: 100

  datasource:
    legacy:
      #      jdbc-url: ${DRP_DB_URL}
      #      username: ${DRP_DB_USERNAME}
      #      password: ${DRP_DB_PASSWORD}
      jdbc-url: jdbc:mariadb://localhost:3306/appdb?serverTimezone=UTC
      username: root
      password: 'pass1234'
      driver-class-name: org.mariadb.jdbc.Driver
      connection-init-sql: SET time_zone = '+00:00'
      pool-name: DEFAULT_POOL
      idle-timeout: 600000
      connection-timeout: 30000
      validation-timeout: 5000
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 1800000
